# Taps
tap "nikitabobko/tap"

# CLI tools
brew "tmux"
brew "fastfetch"
brew "chafa"
brew "lazygit"
brew "neovim"
brew "fzf"
brew "bat"
brew "gh"
brew "glab"
brew "tree"
brew "go"

# Cask apps
cask "ghostty"
cask "nikitabobko/tap/aerospace"

# Fonts
cask "font-iosevka-term-nerd-font"
cask "font-hack-nerd-font"
cask "font-sf-mono"
